### ISSUE TITLE
Exception while sending email

### ISSUE THREAD

**Issue by chintans** [Promact/promact-oauth-server#159]
Exception coming when sending email

```
2016-11-04 05:46:18.2245|0|Promact.Oauth.Server.Controllers.UserController|ERROR|  Resend Mail unsuccessful Failed to convert 'xyzasbklajklsdjfklsdjfsd;fhjsdnjksadhfjsdhfkjsdhfjshdfsdf' to type 'Promact.Oauth.Server.Models.SendGridAPI'.System.InvalidOperationException: Failed to convert 'xyzasbklajklsdjfklsdjfsd;fhjsdnjksadhfjsdhfkjsdhfjshdfsdf' to type 'Promact.Oauth.Server.Models.SendGridAPI'. ---> System.NotSupportedException: TypeConverter cannot convert from System.String.
   at System.ComponentModel.TypeConverter.GetConvertFromException(Object value)
   at System.ComponentModel.TypeConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at System.ComponentModel.TypeConverter.ConvertFromInvariantString(String text)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.ConvertValue(Type type, String value)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.ConfigurationBinder.ConvertValue(Type type, String value)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.BindInstance(Type type, Object instance, IConfiguration config)
   at Microsoft.Extensions.Configuration.ConfigurationBinder.Bind(IConfiguration configuration, Object instance)
   at Microsoft.Extensions.Options.ConfigureFromConfigurationOptions`1.<>c__DisplayClass0_0.<.ctor>b__0(TOptions options)
   at Microsoft.Extensions.Options.ConfigureOptions`1.Configure(TOptions options)
   at Microsoft.Extensions.Options.OptionsCache`1.CreateOptions()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at System.Threading.LazyInitializer.EnsureInitialized[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.Extensions.Options.OptionsCache`1.get_Value()
   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
   at Promact.Oauth.Server.Services.SendGridEmailSender.SendEmail(String email, String subject, String message) in D:\home\site\repository\Promact.Oauth.Server\src\Promact.Oauth.Server\Services\SendGridEmailSender.cs:line 29
   at Promact.Oauth.Server.Repository.UserRepository.SendEmail(ApplicationUser user, String password) in D:\home\site\repository\Promact.Oauth.Server\src\Promact.Oauth.Server\Repository\UserRepository\UserRepository.cs:line 584
   at Promact.Oauth.Server.Repository.UserRepository.<ReSendMail>d__25.MoveNext() in D:\home\site\repository\Promact.Oauth.Server\src\Promact.Oauth.Server\Repository\UserRepository\UserRepository.cs:line 405
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Promact.Oauth.Server.Controllers.UserController.<ReSendMail>d__19.MoveNext() in D:\home\site\repository\Promact.Oauth.Server\src\Promact.Oauth.Server\Controllers\UserController.cs:line 456 
```

/cc @ankit213 @juliepromact

**Comment by ankit213** [comment]
Start date : 04-11-2016
Estimate Time : 3 Hours
End date : 04-11-2016

**Comment by ankit213** [comment]
@hardikbhatt : please check this issue, now it's solved.
